/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CollectionAndReception: {
      address: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
            {
              indexed: false,
              internalType: "enum Status",
              name: "collectedStatus",
              type: "uint8",
            },
          ],
          name: "WasteCollected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "WasteReceived",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "calculateReliability",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "collections",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              internalType: "enum Status",
              name: "status",
              type: "uint8",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "receptions",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "collected",
              type: "bool",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "recordCollection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "recordReception",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "reliability",
          outputs: [
            {
              internalType: "uint256",
              name: "reliabilityScore",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalCollections",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoMarketplace: {
      address: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "fardoNFTAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoListedForSale",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoSold",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "buyFardo",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "fardoNFTContract",
          outputs: [
            {
              internalType: "contract FardoNFT",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "listForSale",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "platformFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
          ],
          name: "rateFardoQuality",
          outputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "sales",
          outputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "updatePrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoNFT: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fardos",
          outputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "qualityRating",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getFardoDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "weight",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "material",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "qualityRating",
                  type: "uint256",
                },
              ],
              internalType: "struct FardoNFT.Fardo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
          ],
          name: "mintFardoNFT",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    WasteRegistry: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "WasteRegistered",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "getWasteDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  components: [
                    {
                      internalType: "uint256",
                      name: "pet",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "aluminum",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct Quantity",
                  name: "quantity",
                  type: "tuple",
                },
              ],
              internalType: "struct Waste",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextWasteId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "registerWaste",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "wastes",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  80002: {
    CollectionAndReception: {
      address: "0xE7609C6FAb936b10ECf6410E91Cd0C53B73Aa1eb",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
            {
              indexed: false,
              internalType: "enum Status",
              name: "collectedStatus",
              type: "uint8",
            },
          ],
          name: "WasteCollected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "WasteReceived",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "calculateReliability",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "collections",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              internalType: "enum Status",
              name: "status",
              type: "uint8",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "receptions",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "collected",
              type: "bool",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "recordCollection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "recordReception",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "reliability",
          outputs: [
            {
              internalType: "uint256",
              name: "reliabilityScore",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalCollections",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoMarketplace: {
      address: "0x6Ddb64Ca2c8F6B5EfdB1752ddB8078B8FF74c42D",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "fardoNFTAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoListedForSale",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoSold",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "buyFardo",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "fardoNFTContract",
          outputs: [
            {
              internalType: "contract FardoNFT",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "listForSale",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "platformFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
          ],
          name: "rateFardoQuality",
          outputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "sales",
          outputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "updatePrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoNFT: {
      address: "0xdd049c9e60A90356D4800568ae7CC8604272580B",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fardos",
          outputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "qualityRating",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getFardoDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "weight",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "material",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "qualityRating",
                  type: "uint256",
                },
              ],
              internalType: "struct FardoNFT.Fardo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
          ],
          name: "mintFardoNFT",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    WasteRegistry: {
      address: "0x4f5D019771312889A4C2E23999640795B58597fA",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "WasteRegistered",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "getWasteDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  components: [
                    {
                      internalType: "uint256",
                      name: "pet",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "aluminum",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct Quantity",
                  name: "quantity",
                  type: "tuple",
                },
              ],
              internalType: "struct Waste",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextWasteId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "registerWaste",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "wastes",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  421614: {
    CollectionAndReception: {
      address: "0xE7609C6FAb936b10ECf6410E91Cd0C53B73Aa1eb",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
            {
              indexed: false,
              internalType: "enum Status",
              name: "collectedStatus",
              type: "uint8",
            },
          ],
          name: "WasteCollected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "WasteReceived",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "calculateReliability",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "collections",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "collector",
              type: "address",
            },
            {
              internalType: "enum Status",
              name: "status",
              type: "uint8",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "receptions",
          outputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recycler",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "collected",
              type: "bool",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "recordCollection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "receivedQuantity",
              type: "tuple",
            },
          ],
          name: "recordReception",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "reliability",
          outputs: [
            {
              internalType: "uint256",
              name: "reliabilityScore",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalCollections",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoMarketplace: {
      address: "0x6Ddb64Ca2c8F6B5EfdB1752ddB8078B8FF74c42D",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "fardoNFTAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoListedForSale",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "FardoSold",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "buyFardo",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "fardoNFTContract",
          outputs: [
            {
              internalType: "contract FardoNFT",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "listForSale",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "platformFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
          ],
          name: "rateFardoQuality",
          outputs: [],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "sales",
          outputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "updatePrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FardoNFT: {
      address: "0xdd049c9e60A90356D4800568ae7CC8604272580B",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fardos",
          outputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "qualityRating",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getFardoDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "weight",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "material",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "qualityRating",
                  type: "uint256",
                },
              ],
              internalType: "struct FardoNFT.Fardo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "material",
              type: "string",
            },
          ],
          name: "mintFardoNFT",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    WasteRegistry: {
      address: "0x4f5D019771312889A4C2E23999640795B58597fA",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "WasteRegistered",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wasteId",
              type: "uint256",
            },
          ],
          name: "getWasteDetails",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  components: [
                    {
                      internalType: "uint256",
                      name: "pet",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "aluminum",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct Quantity",
                  name: "quantity",
                  type: "tuple",
                },
              ],
              internalType: "struct Waste",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextWasteId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          name: "registerWaste",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "wastes",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "pet",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "aluminum",
                  type: "uint256",
                },
              ],
              internalType: "struct Quantity",
              name: "quantity",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
